services:
  sartu_win.app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sartu_win.app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - sartu_win-network
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 5s
      retries: 5

  sartu_win.node:
    image: node:24.11.1
    container_name: sartu_win.node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - sartu_win-network

  sartu_win.nginx:
    image: nginx:alpine
    container_name: sartu_win.nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html                
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      sartu_win.app:
        condition: service_healthy
    networks:
      - sartu_win-network

  sartu_win.db:
    image: mysql:8.0
    container_name: sartu_win.db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: rk_sartu
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
    volumes:
      - sartu_win_db_data:/var/lib/mysql
    networks:
      - sartu_win-network

volumes:
  sartu_win_db_data:

networks:
  sartu_win-network:
    driver: bridge