version: '3.8'
services:
  sartu.app:
    build: .
    container_name: sartu.app
    volumes:
      - .:/var/www/html
    networks:
      - sartu-network

  sartu.nginx:
    image: nginx:alpine
    container_name: sartu.nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sartu.app
    networks:
      - sartu-network

  sartu.db:
    image: mysql:8.0
    container_name: sartu.db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rk_sartu
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - sartu_db_data:/var/lib/mysql
    networks:
      - sartu-network

volumes:
  sartu_db_data:

networks:
  sartu-network:
    driver: bridge